-- MEP EAD | Histórico de logins autenticados exibido somente aos gestores.

create table if not exists public.acessos_plataforma (
    id bigint generated by default as identity primary key,
    usuario_id uuid not null references public.usuarios(id) on delete cascade,
    acessado_em timestamptz not null default now()
);

create index if not exists acessos_plataforma_acessado_em_idx
    on public.acessos_plataforma (acessado_em desc);

create index if not exists acessos_plataforma_usuario_id_idx
    on public.acessos_plataforma (usuario_id, acessado_em desc);

alter table public.acessos_plataforma enable row level security;

create or replace function public.registrar_acesso_plataforma()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_usuario_id uuid;
    v_acesso_id bigint;
begin
    if auth.uid() is null then
        raise exception 'Sessão não encontrada.';
    end if;

    select u.id
      into v_usuario_id
      from public.usuarios u
     where u.auth_id = auth.uid()
       and u.ativo = true
     limit 1;

    if v_usuario_id is null then
        raise exception 'Usuário não encontrado ou acesso inativo.';
    end if;

    insert into public.acessos_plataforma (usuario_id)
    values (v_usuario_id)
    returning id into v_acesso_id;

    return jsonb_build_object('success', true, 'id', v_acesso_id);
end;
$$;

create or replace function public.listar_acessos_plataforma(p_limite integer default 12)
returns table (
    id bigint,
    usuario_id uuid,
    nome text,
    perfil text,
    foto_url text,
    acessado_em timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
    if auth.uid() is null or not exists (
        select 1
          from public.usuarios gestor
         where gestor.auth_id = auth.uid()
           and lower(gestor.perfil) = 'gestor'
           and gestor.ativo = true
    ) then
        raise exception 'Acesso permitido somente para gestores.';
    end if;

    return query
    select a.id,
           a.usuario_id,
           u.nome,
           u.perfil,
           u.foto_url,
           a.acessado_em
      from public.acessos_plataforma a
      join public.usuarios u on u.id = a.usuario_id
     order by a.acessado_em desc
     limit greatest(1, least(coalesce(p_limite, 12), 50));
end;
$$;

revoke all on table public.acessos_plataforma from anon, authenticated;
revoke all on function public.registrar_acesso_plataforma() from public;
revoke all on function public.listar_acessos_plataforma(integer) from public;
grant execute on function public.registrar_acesso_plataforma() to authenticated;
grant execute on function public.listar_acessos_plataforma(integer) to authenticated;

comment on table public.acessos_plataforma is
    'Registra o instante de cada login autenticado na plataforma MEP EAD.';
